# Generated by Django 2.2.6 on 2019-10-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sith',
            options={'verbose_name': 'Ситх', 'verbose_name_plural': 'Ситхи'},
        ),
    ]
