# Generated by Django 2.2.6 on 2019-10-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191016_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='planet',
            field=models.CharField(default='null', max_length=255, verbose_name='Планета обитания'),
        ),
        migrations.AlterField(
            model_name='sith',
            name='planet',
            field=models.CharField(default='null', max_length=255, verbose_name='Планета обитания'),
        ),
        migrations.DeleteModel(
            name='Planet',
        ),
    ]
