# Generated by Django 2.2.6 on 2019-10-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191017_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sith',
            name='recruits',
        ),
        migrations.AddField(
            model_name='recruit',
            name='is_shadow_hands',
            field=models.BooleanField(default=False, verbose_name='Рука тени'),
        ),
    ]
