# Generated by Django 2.2.5 on 2019-10-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191017_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='is_shadow_hands',
        ),
        migrations.AddField(
            model_name='recruit',
            name='shadow_hands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Sith', verbose_name='Рука тени'),
        ),
    ]
